services:
  db:
    image: postgres:latest
    container_name: regle-de-trois-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: regle_de_trois
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d regle_de_trois"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
  backend:
    image: regle-de-trois-backend
    build: ./backend
    container_name: regle-de-trois-backend
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@regle-de-trois-db:5432/regle_de_trois?schema=public
      - NODE_ENV=development
      - PORT=3001
    networks:
      - app-network
  frontend:
    image: regle-de-trois-frontend
    build: ./frontend
    container_name: regle-de-trois-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network:
    driver: bridge
