services:
  db:
    image: postgres:latest
    container_name: regle-de-trois-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: regle_de_trois
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: regle-de-trois-backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/regle_de_trois?schema=public
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: regle-de-trois-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm start

volumes:
  db_data:
